### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by santacruz123** [coffeescript-cookbook/coffeescript-cookbook.github.io#127]

**Comment by djpowers** [comment]
This is related to #122 

According to that issue, it is unknown who owns the domain, so unfortunately the fix cannot be made.

**Comment by sukima** [comment]
![r_i_p_gravestone](https://cloud.githubusercontent.com/assets/70075/5675165/d859dcd4-9785-11e4-8081-cabf063ec68f.png)

**Comment by djpowers** [comment]
@sukima Too funny! :laughing: :skull:

If all else fails, the domain registration expires April 29, 2018, so we may be able to resurrect it then.

**Comment by lolmaus** [comment]
Done! I have:

* forked the repo,
* adjusted Jekyll config,
* and fixed all links to be servable from Github Pages.

https://lolmaus.github.io/coffeescript-cookbook/

We can make it servable via this organization's Github Pages:


Please add me to the organization with admin rights so that i can:

1. rename the current `master` branch to `master-old`;
2. push the updated codebase to the main project's `master` branch;
3. make the new branch default;
4. rename the project on Github (the name will be part of the URL);
5. update project description to point at the new URL.

**Comment by lolmaus** [comment]
Done! I have:

* forked the repo,
* adjusted Jekyll config,
* and fixed all links to be servable from Github Pages.

https://lolmaus.github.io/coffeescript-cookbook/

We can make it servable via this organization's Github Pages with the following URL:

```
https://coffeescript-cookbook.github.io/
```

To achieve this, the following steps are required:

1. rename the current `master` branch to `master-old`;
2. push the updated codebase to the main project's `master` branch;
3. adjust Jekyll config `baseurl`;
4. make the new branch default;
5. rename the project on Github (the name will be part of the URL);
6. update project description to point at the new URL;
7. update site links to point at the new URL.

If you add me to the organization with admin rights, i will gladly perform those steps.

**Comment by peterhellberg** [comment]
@lolmaus I added you to the contributors team now, I’ll also add you to the Administrators team.

**Comment by lolmaus** [comment]
@peterhellberg, i don't see myself listed here: https://github.com/orgs/coffeescript-cookbook/people .

And neither do i have the Settings section on the project page.

**Comment by lolmaus** [comment]
Ah sorry, i had to accept the invitation. I'm in, proceeding with website restoration.

**Comment by peterhellberg** [comment]
:+1:

**Comment by lolmaus** [comment]
And we're live! https://coffeescript-cookbook.github.io/

It might be reasonable to keep #122 open, the domain owner might show up. We should be able to switch back to the custom domain by creating a `CNAME` file and waiting for fifteen minutes.

**Comment by markusgattol** [comment]
the URL on https://github.com/coffeescript-cookbook is still the old one, needs changing too

**Comment by lolmaus** [comment]
> @markusgattol 
> the URL on https://github.com/coffeescript-cookbook is still the old one, needs changing too

Only organization owner seems to be able to do that?

**Comment by peterhellberg** [comment]
@markusgattol @lolmaus I’ve now changed it to http://coffeescript-cookbook.github.io/

**Comment by lolmaus** [comment]
@peterhellberg Good, by why `http`? Here in Moscow, free wifi spots are used to show extra ads over non-encrypted connections. Chrome is gonna mark all non-encrypted connections as insecure.

**Comment by peterhellberg** [comment]
@lolmaus My bad, I’ve updated it to https now :)
