### ISSUE TITLE
Chapter index is not visible anymore

### ISSUE THREAD

**Issue by dmitry** [coffeescript-cookbook/coffeescript-cookbook.github.io#142]
Looks like pages not generated completely. Please trigger regeneration.

**Comment by simonneutert** [comment]
@amsul @blowmage or @SamiPussinen maybe you do some magic for us readers out here 🎄

**Comment by blowmage** [comment]
Chapter contents are showing in the side navigation again.

**Comment by simonneutert** [comment]
sorry, but not on the front page. thanks for sticking to it!
![bildschirmfoto 2017-01-11 um 17 38 56](https://cloud.githubusercontent.com/assets/8125726/21857190/e4958e3a-d824-11e6-8950-d1fc32b5b460.png)

**Comment by blowmage** [comment]
Clear your cache and refresh. I see chapters on the homepage as well as the chapter pages.

**Comment by simonneutert** [comment]
my bad, thank you so much for making this work!
