### ISSUE TITLE
Arrays / Max Array Value / faulty example

### ISSUE THREAD

**Issue by log69** [coffeescript-cookbook/coffeescript-cookbook.github.io#149]
The example is wrong at the "Solution" section of "Max Array Value" in chapter "Arrays". 

The following does not work:
 `Math.max [12, 32, 11, 67, 1, 3]`

Instead it could be something like:
`Math.max.apply null, [12, 32, 11, 67, 1, 3]`

**Comment by sukima** [comment]
CoffeeScript [supports splats](http://coffeescript.org/#splats). One should use that instead of `apply`:

```js
Math.max [12, 32, 11, 67, 1, 3]...
```

**Comment by log69** [comment]
I misunderstood the dots, thanks.
