### ISSUE TITLE
using several git programs simultaneously

### ISSUE THREAD

**Issue by AtomicNess123** [coffeescript-cookbook/coffeescript-cookbook.github.io#154]
I have a question of a basic nature that no tutorial has been able to answer to me. I was working with SourceTree in a local repo pushing to Github.com. At some point I decided to use Github Desktop, so I added the local repo and started to push to Github.com. I did not like this software, so I went back to SourceTree. Opened my project there but changes were not being tracked anymore. I wonder if one can use two git managers for tracking changes or else I don't know what went wrong.

**Comment by lolmaus** [comment]
@Gahamelas This repository is not the right place to ask such questions. You should use StackOverflow or some forums instead.
